apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: retail
  description: Environment management related microservices
spec:
  owner: retail-team
  domain: online-stores
---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cart
  description: cart microservice
  annotations:
    torque.io/environment:
      - "Online Boutique Development-20240118T13395902"
    torque.io/lifecycle: "activity_type"
    jenkins.io/job-full-name: "cli/torque-cli-docker"
  tags:
    - retail
spec:
  type: aws
  owner: retail-team
  lifecycle: production
  system: retail
  dependsOn:
    - resource:default/retail-cache
    - resource:default/retail-db
  providesApis:
    - online-boutique-apis
---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  description: frontend microservice
  annotations:
    "torque.io/space": "01-Development"
    "torque.io/lifecycle": "activity_type"
    "jenkins.io/job-full-name": "cli/torque-cli-docker"
  tags:
    - retail
spec:
  type: service
  owner: retail-team
  lifecycle: production
  system: retail
  dependsOn:
    - resource:default/retail-cache
    - resource:default/retail-db
  providesApis:
    - online-boutique-apis
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: product-catalog
  description: product-catalog microservice
  annotations:
    "torque.io/space": "01-Development"
    "torque.io/lifecycle": "activity_type"
    "jenkins.io/job-full-name": "cli/torque-cli-docker"
  tags:
    - retail
spec:
  type: service
  owner: retail-team
  lifecycle: production
  system: retail
  dependsOn:
    - resource:default/retail-cache
    - resource:default/retail-db
  providesApis:
    - online-boutique-apis
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: currency
  description: currency microservice
  annotations:
    "torque.io/space": "01-Development"
    "torque.io/lifecycle": "activity_type"
    "jenkins.io/job-full-name": "cli/torque-cli-docker"
  tags:
    - retail
spec:
  type: service
  owner: retail-team
  lifecycle: production
  system: retail
  dependsOn:
    - resource:default/retail-cache
    - resource:default/retail-db
  providesApis:
    - online-boutique-apis
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment
  description: payment microservice
  annotations:
    "torque.io/space": "01-Development"
    "torque.io/lifecycle": "activity_type"
    "jenkins.io/job-full-name": "cli/torque-cli-docker"
  tags:
    - retail
spec:
  type: service
  owner: retail-team
  lifecycle: production
  system: retail
  dependsOn:
    - resource:default/retail-cache
    - resource:default/retail-db
  providesApis:
    - online-boutique-apis
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shipping
  description: shipping microservice
  annotations:
    "torque.io/space": "01-Development"
    "torque.io/lifecycle": "activity_type"
    "jenkins.io/job-full-name": "cli/torque-cli-docker"
  tags:
    - retail
spec:
  type: service
  owner: retail-team
  lifecycle: production
  system: retail
  dependsOn:
    - resource:default/retail-cache
    - resource:default/retail-db
  providesApis:
    - online-boutique-apis
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: email
  description: email microservice
  annotations:
    "torque.io/space": "01-Development"
    "torque.io/lifecycle": "activity_type"
    "jenkins.io/job-full-name": "cli/torque-cli-docker"
  tags:
    - retail
spec:
  type: service
  owner: retail-team
  lifecycle: production
  system: retail
  dependsOn:
    - resource:default/retail-cache
    - resource:default/retail-db
  providesApis:
    - online-boutique-apis
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: checkout
  description: checkout microservice
  annotations:
    "torque.io/space": "03-Live"
    "torque.io/lifecycle": "activity_type"
    jenkins.io/job-full-name: 'cli/torque-cli-docker'
    github.com/project-slug: 'QualiNext/cs2018'
  tags:
    - retail
spec:
  type: service
  owner: retail-team
  lifecycle: production
  system: retail
  dependsOn:
    - resource:default/retail-cache
    - resource:default/retail-db
  providesApis:
    - online-boutique-apis
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: recommendation
  description: recommendation microservice
  annotations:
    "torque.io/space": "01-Development"
    "torque.io/lifecycle": "activity_type"
    "jenkins.io/job-full-name": "cli/torque-cli-docker"
  tags:
    - retail
spec:
  type: service
  owner: retail-team
  lifecycle: production
  system: retail
  dependsOn:
    - resource:default/retail-cache
    - resource:default/retail-db
  providesApis:
    - online-boutique-apis
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ads
  description: ads microservice
  annotations:
    "torque.io/space": "03-Live"
    "torque.io/lifecycle": "activity_type"
    "jenkins.io/job-full-name": "cli/torque-cli-docker"
  tags:
    - retail
spec:
  type: service
  owner: retail-team
  lifecycle: production
  system: retail
  dependsOn:
    - resource:default/retail-cache
    - resource:default/retail-db
  providesApis:
    - online-boutique-apis
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: load-generator
  description: load-generator tool
  annotations:
    "torque.io/space": "01-Development"
    "torque.io/lifecycle": "activity_type"
    "jenkins.io/job-full-name": "cli/torque-cli-docker"
  tags:
    - retail
    - tools
spec:
  type: service
  owner: retail-team
  lifecycle: experimental
  system: retail
  dependsOn:
    - resource:default/retail-cache
    - resource:default/retail-db
  providesApis:
    - online-boutique-apis
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: online-boutique-apis
spec:
  type: openapi
  lifecycle: production
  owner: retail-team
  definition:
    $text: https://github.com/QualiNext/test-spec2-public/blob/master/test.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: retail-cache
  description: Stores all accounts details and users transactions
spec:
  type: cache
  owner: retail-team
  system: retail
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: retail-db
  description: Stores all accounts details and users transactions
  links:
    - url: https://dashboard.example.com
      title: 'connection string'
      icon: dashboard
spec:
  type: database
  owner: retail-team
  system: retail

